#!/bin/bash
set -euo pipefail
export HOME="${HOME:-/home/developer}"
export PATH="${HOME}/studio/.venv/bin:${HOME}/.local/bin:/usr/local/bin:/opt/node-current/bin:$PATH"
if [ -f "${HOME}/.constructor-fabric-ai.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "${HOME}/.constructor-fabric-ai.env"
  set +a
fi
LOG="${HOME}/studio/auto-bootstrap.log"
exec >>"$LOG" 2>&1
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Constructor Fabric auto-bootstrap started"

provider="$(printenv LLM_PROVIDER || true)"
if [ -z "$provider" ]; then provider=openai; fi
case "$provider" in openai|claude) ;; *) provider=openai ;; esac
if [ "$provider" = "claude" ]; then
  model="$(printenv CLAUDE_MODEL || true)"
  if [ -z "$model" ]; then model=claude-sonnet-4-6; fi
else
  model="$(printenv OPENAI_MODEL || true)"
  if [ -z "$model" ]; then model=gpt-5.5; fi
fi
token="$(printenv API_TOKEN || true)"
if [ -z "$token" ] && [ "$provider" = "claude" ]; then token="$(printenv ANTHROPIC_API_KEY || true)"; fi
if [ -z "$token" ] && [ "$provider" = "openai" ]; then token="$(printenv OPENAI_API_KEY || true)"; fi

project_name="Constructor Fabric Workspace"
slug="constructor-fabric-workspace"
root="${HOME}/workspaces/$slug"
mkdir -p "$root"
cat > "$root/.constructor-fabric.json" <<JSON
{
  "provider": "$provider",
  "model": "$model",
  "api_token_set": $(if [ -n "$token" ]; then echo true; else echo false; fi),
  "source": "Virtuozzo install form",
  "trainer": "code-server-webview"
}
JSON
{
  echo "LLM_PROVIDER=$provider"
  echo "OPENAI_MODEL=$model"
  echo "CLAUDE_MODEL=$model"
  if [ -n "$token" ]; then
    echo "API_TOKEN=$token"
    if [ "$provider" = "claude" ]; then echo "ANTHROPIC_API_KEY=$token"; else echo "OPENAI_API_KEY=$token"; fi
  fi
} > "$root/.env.constructor-fabric"
# Continue config is generated by install-ides.sh / manifest with schema validation.
# Do not write a second legacy config here; late overwrites can break Continue.
# Also push credentials into the VS Code / Codium integrated terminal.
mkdir -p "${HOME}/.config/VSCodium/User" "${HOME}/.config/Code/User"
for udir in "${HOME}/.config/VSCodium/User" "${HOME}/.config/Code/User"; do
  if [ "$provider" = "claude" ] && [ -n "$token" ]; then
    cat > "$udir/settings.json" <<VSCODESETTINGS
{
  "terminal.integrated.env.linux": {
    "ANTHROPIC_API_KEY": "$token",
    "CLAUDE_MODEL": "$model",
    "LLM_PROVIDER": "$provider"
  }
}
VSCODESETTINGS
  elif [ "$provider" = "openai" ] && [ -n "$token" ]; then
    cat > "$udir/settings.json" <<VSCODESETTINGS
{
  "terminal.integrated.env.linux": {
    "OPENAI_API_KEY": "$token",
    "OPENAI_MODEL": "$model",
    "LLM_PROVIDER": "$provider"
  }
}
VSCODESETTINGS
  fi
done
# The Trainer webview is the single source of training content; remove the
# legacy copy/paste prompt file from older images so it cannot drift.
rm -f "$root/CONSTRUCTOR_FABRIC_PROMPTS.md"
if [ ! -f "$root/README.md" ]; then
  cat > "$root/README.md" <<README
# Constructor Fabric Workspace

This workspace was initialized automatically from the marketplace installation form.

- Provider: $provider
- Model: $model
- API token configured: $(if [ -n "$token" ]; then echo yes; else echo no; fi)

The Constructor Fabric Trainer opens automatically inside the IDE and guides you
step by step. To reopen it: press F1 and run "Constructor Fabric: Open Trainer".
README
fi

cfs init --no-cache --project-root "$root" --install-dir .cf-studio --project-name "$slug" --force --yes
# init --force backs up the build-time .cf-studio before re-initializing; the
# backup only holds generated state and would litter every fresh workspace.
rm -rf "$root"/.cf-studio.*.backup
cfs generate-agents --root "$root" -y
(cd "$root" && cfs agents --json > "${HOME}/studio/workspace-agents.json" && python3 - <<'PYAGENTS'
import json, sys
from pathlib import Path
text=json.dumps(json.loads((Path.home()/'studio/workspace-agents.json').read_text())).lower()
required=['windsurf','claude','copilot','openai']
missing=[name for name in required if name not in text]
if missing:
    raise SystemExit('Missing generated IDE/agent integrations: '+', '.join(missing))
print('Generated Constructor Fabric integrations for: '+', '.join(required))
PYAGENTS
)
# Final step of Studio deployment: refresh the Studio runtime and the installed
# kits to their latest published versions (kits are fetched from their registered
# GitHub sources). Non-fatal: the baked Studio/kit versions already work.
(cd "$root" && cfs update --with-kits yes --yes) \
  || echo "WARNING: cfs update --with-kits failed — continuing with baked Studio/kit versions"
(cd "$root" && cfs validate --json) || true
# Greenfield precondition: the trainee must start with an empty artifact tree.
# Only warn (never fail) — on redeploys the trainee may legitimately have work
# in progress, and the Trainer's own state tracks that.
if [ ! -f "$root/.constructor-fabric-trainer/state.json" ]; then
  for d in architecture src .cf-studio/artifacts; do
    if [ -e "$root/$d" ]; then
      echo "WARNING: fresh workspace already contains '$d/' — greenfield training expects it to be absent"
    fi
  done
fi
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Constructor Fabric auto-bootstrap finished for $root"
